#!/bin/bash
# Script automático DNS en Ubuntu Server

echo "Actualizando el sistema..."
apt-get update -y
apt-get upgrade -y

echo "Instalando servicio BIND9..."
apt-get install bind9 bind9utils -y

# Variables
DOMINIO="reprobados.com"
IP="192.168.1.109"
ZONAS="/etc/bind/zones"
ARCHIVO_ZONA="db.${DOMINIO}"

echo "Creando carpeta de zonas..."
mkdir -p ${ZONAS}
chown bind:bind ${ZONAS}

echo "Generando la zona del dominio..."
cat > ${ZONAS}/${ARCHIVO_ZONA} << EOF
\$TTL 86400
@ IN SOA ns1.${DOMINIO}. admin.${DOMINIO}. (
    $(date +%Y%m%d)01 ; Serial
    28800 ; Refresh
    7200 ; Retry
    864000 ; Expire
    86400 ; Minimum TTL
)
; Nameserver
@ IN NS ns1.${DOMINIO}.
ns1 IN A ${IP}
@ IN A ${IP}
www IN A ${IP}
EOF

echo "Configurando named.conf.local..."
echo "zone \"${DOMINIO}\" { type master; file \"${ZONAS}/${ARCHIVO_ZONA}\"; };" >> /etc/bind/named.conf.local

echo "Verificando configuración..."
named-checkconf

echo "Reiniciando BIND9..."
systemctl restart bind9
systemctl status bind9
echo "DNS configurado correctamente."
